### ISSUE TITLE
User Authentication Review

### ISSUE THREAD

**Issue by hongyang90** [hongyang90/BassNimbus#2]
Created the splash banner with signup and login modal forms. Added demo user login. Errors are rendered and cleared on the modal forms. Created main navbar with dropdown signout. Set main page as auth route and discover page as protected route.

**Comment by andywynkoop** [comment]
Hey, this looks pretty good so far - here are a few changes I think you should make:
- [ ] Input fields on form look like they have "depth" - style them to look flatter
- [ ] form should we a little wider
- [ ] Overlay should be a little less transparent
- [ ] Your cloud looks squashed
- [ ] I think the text in the session buttons needs to be a little smaller in the nav bar
- [ ] The `X` for your modal should be in the top right corner of the screen - If you want to leave it in the modal instead, you should still style it to match
- [ ] Going to a random route like `/bologna` should redirect to `/` or render a 404 page
- [ ] errors seem to push the form title over the logo - this shouldn't happen. Ideally nothing else on the page should move when errors are rendered
- [ ] `Cannot read property 'classList' of null`
- [ ] the form should not resize when the screen resizes - use a fixed width
- [ ] I can visit `/dashboard` without getting redirected to `/`. I still see the splash page, but this is confusing
- [ ] For final production, remember to remove all console logs and redux logger
